import "../globals.css";
import Navbar from '@/components/Navbar.jsx'
import { NextProvider } from '@/utils/context.js'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextProvider> 
           <Navbar />
           {children}
        </NextProvider>
      </body>
    </html>
  );
}
